spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:8080}
    username: ${RABBITMQ_USERNAME:abc}
    password: ${RABBITMQ_PASSWORD:xyz}

firebase:
  google-credentials: src/main/resources/fcm-key.json