spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:8080}
    username: ${RABBITMQ_USERNAME:abc}
    password: ${RABBITMQ_PASSWORD:xyz}
  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@mobile-database.xpkoema.mongodb.net/?retryWrites=true&w=majority&appName=Mobile-Database
      database: ${MONGODB_DATABASE:notification-service}

firebase:
  google-credentials: fcm-key.json