spring:
  application:
    name: notification-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:8080}
    username: ${RABBITMQ_USERNAME:abc}
    password: ${RABBITMQ_PASSWORD:xyz}
    message-queue-name: message
    email-queue-name: email
    exchange-name: notification